### ISSUE TITLE
Second slider

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/murkosha#4]
Second slider is easier than the main one.

It is required to create a `cms` wrapper for the slider. It should:

1. be possible to add or remove slides
2. be possible to change any text on slides

<img width="1280" alt="2017-04-26 14 26 42" src="https://cloud.githubusercontent.com/assets/4660275/25432264/6652398c-2a8c-11e7-8b42-34ca0d03b4a0.png">

**Comment by shestera** [comment]
Done
